"""adds relationship bettwen 'User', 'Post' and 'Comment'

Revision ID: ae2d7fcf9991
Revises: 94ebc59de9da
Create Date: 2025-10-31 03:06:03.838086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2d7fcf9991'
down_revision: Union[str, Sequence[str], None] = '94ebc59de9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', sa.String(), nullable=False))
    op.drop_column('comments', 'author_name')
    op.add_column('posts', sa.Column('author_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'author_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    op.add_column('comments', sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###
