"""fixs posts_tags table

Revision ID: e625e622832a
Revises: 6ca5485f85d7
Create Date: 2025-10-31 08:36:22.767773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e625e622832a'
down_revision: Union[str, Sequence[str], None] = '6ca5485f85d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts_tags', 'post_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts_tags', 'tag_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts_tags', 'tag_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts_tags', 'post_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
